### ISSUE TITLE
Failo nurodymas per command line

### ISSUE THREAD

**Issue by aidiss** [vilisperis/Teksto-atrinkejas-is-pdf-jpeg#1]
Programa turėtų palaikyti galimybę nurodyti failą per command line:

```t
python main.py failo-pavadinimas.pdf
```

**Comment by vilisperis** [comment]
niekaip nesugalvoju kaip tai padaryti,

main.py failo-pavadinimas.pdf



2019-10-16, tr, 20:08 Aidis Stukas <notifications@github.com> rašė:

**Comment by aidiss** [comment]
Programos kuri tik ispausdina pirmą command line argumentą (tarkim - failo-pavadinimas.pdf pavyzdys
```
# programa.py
import sys
arguments = sys.argv[1:]
filename = arguments[0]
```

`programa.py failo-pavadinimas.pdf` ispausdintu "failo-pavadinimas.pdf"
